export CUDA_VISIBLE_DEVICES=1,2
python main.py \
--mode test \
--batch_size 1 \
--accumulate_grad_batches 16 \
--dataset lastfm_data \
--data_dir ./hf_data/lastfm \
--cans_num 20 \
--prompt_path ./prompt/artist.txt \
--rec_embed SASRec \
--llm_tuning lora \
--llm_path ./hf_model \
--rec_model_path ./rec_model/lastfm.pt \
--ckpt_path ./checkpoints/lastfm_peft/epoch=03-metric=0.541.ckpt \
--ckpt_head_path ./checkpoints/lastfm_peft_prelim_layer30/epoch=13-metric=0.557.ckpt \
--output_dir ./output/lastfm/ \
--log_dir lastfm_logs \
--lr_warmup_start_lr 7e-6 \
--lr 7e-4 \
--lr_decay_min_lr 7e-6 \
--max_epochs 5